# BEGIN ANSIBLE MANAGED BLOCK
services:

  symbios-webui:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./webui:/app
      - ./config:/config
      - ./log:/log
      - /var/log:/var/log:ro
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_SECRET_KEY=symbios-change-this-in-production
      - CONFIG_PATH=/config/inventory.yml
      - LDAP_URI=ldap://openldap
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      - traefik.enable=true
      - traefik.http.routers.symbios-ui.rule=Host(`symbios.local`)
      - traefik.http.routers.symbios-ui.entrypoints=https
      - traefik.http.routers.symbios-ui.tls=true
      - traefik.http.services.symbios-ui.loadbalancer.server.port=8080
      - traefik.http.routers.symbios-ui.service=symbios-ui
      - traefik.http.routers.symbios-ui.tls.certresolver=symbios-pki
      - traefik.docker.network=traefik
    networks:
      - traefik

networks:
  traefik:
    external: true
# END ANSIBLE MANAGED BLOCK
