# BEGIN ANSIBLE MANAGED BLOCK

services:
  traefik:
    image: traefik:latest
    entrypoint: ["/bin/sh", "-c", "cp /ca/symbios-pki-ca.crt /usr/local/share/ca-certificates/ && update-ca-certificates 2>/dev/null; exec /usr/local/bin/traefik --configfile=/etc/traefik/traefik.yml"]
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      traefik:
        ipv4_address: 192.168.41.200
    ports:
      - 80:80
      - 443:443
      - 636:636
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
      - ./providers:/etc/traefik/providers.local
      - ./providers/symbios-pki-ca.pem:/ca/symbios-pki-ca.crt:ro
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./log:/log
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`traefik.{{ default_domain }}`)
      - traefik.http.routers.traefik.entrypoints=https
      - traefik.http.routers.traefik.middlewares=secHeaders@file,authelia@file
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.tls=true
      - traefik.http.routers.traefik.tls.certresolver={{ acme_resolver }}
      - traefik.http.middlewares.to-https.redirectscheme.scheme=https
networks:
  traefik:
    external: true
# END ANSIBLE MANAGED BLOCK
