# SymbiOS - Debian-based server management platform
# Copyright (C) 2025  SymbiOS Contributors
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
# docs:
#   short_description: Deploy the RustDesk remote desktop server
#   description: Deploys RustDesk server (hbbs/hbbr) for self-hosted remote desktop connections. Uses raw TCP/UDP ports, no Traefik.
#   author: Oliver Bohlen
#   version: '1.0'
#   license: GPLv3
#   copyright: Copyright 2026, Oliver Bohlen
#   min_ansible_version: '2.11'
#   platforms:
#   - name: Debian
#     versions:
#     - '13'
#   category: Service
#   service_control:
#     services:
#     - name: rustdesk
#       type: docker
#       compose_file: /home/docker/rustdesk/docker-compose.yml
#       status: test -d /home/docker/rustdesk || exit 2; docker compose -f /home/docker/rustdesk/docker-compose.yml ps | grep -q "Up "
#     logs:
#     - name: rustdesk
#       command: docker compose -f /home/docker/rustdesk/docker-compose.yml logs -f --tail=100
#   actions:
#     uninstall: docker compose -f /home/docker/rustdesk/docker-compose.yml down
#     start: docker compose -f /home/docker/rustdesk/docker-compose.yml up -d
#     stop: docker compose -f /home/docker/rustdesk/docker-compose.yml down
#     restart: docker compose -f /home/docker/rustdesk/docker-compose.yml restart
#     reload: docker compose -f /home/docker/rustdesk/docker-compose.yml up -d
#
---
- name: rustdesk setup
  hosts: all

  vars:
    service_name: rustdesk
    service_domain: "{{ service_name }}.{{ base_domain }}"
    this_arch: "{{ '-arm64v8' if ansible_architecture == 'aarch64' }}"

  tasks:

    - name: Allow port 21115:21119/tcp
      community.general.ufw:
        rule: allow
        port: '21115:21119'
        proto: tcp

    - name: Allow port 21116/udp
      community.general.ufw:
        rule: allow
        port: '21116'
        proto: udp

    - name: /home/docker/{{ service_name }}/docker-compose.yml Container Configuration
      blockinfile:
        path: /home/docker/{{ service_name }}/docker-compose.yml
        create: yes
        mode: 0440
        owner: root
        group: docker
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
        block: |
          
          services:
            {{ service_name }}-hbbs:
              ports:
                - 21115:21115
                - 21116:21116
                - 21116:21116/udp
                - 21118:21118
              image: rustdesk/rustdesk-server:latest{{this_arch}}
              command: hbbs -r {{ service_domain }}:21117 -k _
              volumes:
                - ./data:/root
              networks:
                - {{ service_name }}
              depends_on:
                - {{ service_name }}-hbbr
              restart: unless-stopped
             
            {{ service_name }}-hbbr:
              ports:
                - 21117:21117
                - 21119:21119
              image: rustdesk/rustdesk-server:latest{{this_arch}}
              command: hbbr -k _
              volumes:
                - ./data:/root
              networks:
                - {{ service_name }}
              restart: unless-stopped
             
          networks:
            {{ service_name }}:
              external: false
        backup: yes
      notify: Restart rustdesk

    - name: /usr/local/sbin/runchecks.d/symbios-healthcheck-rustdesk.check
      ansible.builtin.blockinfile:
        path: /usr/local/sbin/runchecks.d/symbios-healthcheck-rustdesk.check
        mode: "0400"
        owner: root
        group: root
        create: yes
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
        block: |
          # Healthcheck for rustdesk (container)
          if ! docker ps | grep -q "rustdesk"
          then
            g_echo_error "Healthcheck failed for rustdesk: container not running"
          fi
        backup: yes
        validate: /bin/bash -n %s


  handlers:

    - name: Restart rustdesk
      ansible.builtin.shell: docker compose up -d --force-recreate
      args:
        chdir: /home/docker/{{ service_name }}

