# SymbiOS - Debian-based server management platform
# Copyright (C) 2025  SymbiOS Contributors
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# docs:
#   short_description: Configure automated system updates
#   description: Sets up periodic automatic updates 6:05am of the host OS packages via a cron job, keeping the system up2date without manual intervention.
#   author: Oliver Bohlen
#   version: '1.0'
#   license: GPLv3
#   copyright: Copyright 2026, Oliver Bohlen
#   min_ansible_version: '2.11'
#   platforms:
#   - name: Debian
#     versions:
#     - '13'
#   category: Maintenance
#   service_control:
#     services:
#     - name: autoupdate
#       type: cron
#       file: /etc/cron.d/autoupdate_local
#       status: test -f /etc/cron.d/autoupdate_local || exit 2
#     logs:
#     - name: autoupdate
#       command: tail -F /var/log/syslog | grep autoupdate
#   actions:
#     enable: sed -i 's/^#//' /etc/cron.d/autoupdate_local
#     disable: sed -i 's/^/#/' /etc/cron.d/autoupdate_local
#     run now: /usr/local/sbin/autoupdate.sh

---
- name: Autoupdate
  hosts: all
  tasks:

    - name: Create updates dir /usr/local/sbin/autoupdate.d
      ansible.builtin.file:
        path: /usr/local/sbin/autoupdate.d
        owner: root
        group: root
        state: directory
        mode: "0700"

    - name: /usr/local/sbin/autoupdate.sh
      ansible.builtin.copy:
        src: /home/SymbiOS/scripts/autoupdate.sh
        dest: /usr/local/sbin/autoupdate.sh
        mode: "0500"
        owner: root
        group: root
        backup: yes

    - name: /etc/cron.d/autoupdate_local
      blockinfile:
        path: /etc/cron.d/autoupdate_local
        mode: "0400"
        owner: root
        group: root
        create: yes
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
        block: |
          ## Auto-Update
          5 6 * * * root /usr/local/sbin/autoupdate.sh
        backup: yes

    - name: Register playbook as installed
      ansible.builtin.command: symbios-state.sh set base-services/autoupdate.yml
      changed_when: false
