# SymbiOS - Debian-based server management platform
# Copyright (C) 2025  SymbiOS Contributors
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# docs:
#   short_description: Configure automated backups
#   description: Installs a scheduled backup job (cron) that backs up SymbiOS configuration and service data to the configured backup target.
#   author: Oliver Bohlen
#   version: '1.0'
#   license: GPLv3
#   copyright: Copyright 2026, Oliver Bohlen
#   min_ansible_version: '2.11'
#   platforms:
#   - name: Debian
#     versions:
#     - '13'
#   category: Backup
#   service_control:
#     services:
#     - name: backup
#       type: cron
#       file: /etc/cron.d/backup_local
#       status: test -f /etc/cron.d/backup_local || exit 2
#     logs:
#     - name: backup
#       command: tail -F /var/log/syslog | grep backup
#   actions:
#     enable: sed -i 's/^#//' /etc/cron.d/backup_local
#     disable: sed -i 's/^/#/' /etc/cron.d/backup_local
#     run now: /usr/local/sbin/backup.sh

---
- name: Backups
  hosts: all
  tasks:
    - name: Install Packages
      apt:
        name:
          - rsync
        update_cache: no
        install_recommends: no

    - name: Create checks dir /usr/local/sbin/backup.d
      ansible.builtin.file:
        path: /usr/local/sbin/backup.d
        owner: root
        group: root
        state: directory
        mode: '0700'

    - name: /usr/local/sbin/backup.sh
      blockinfile:
        path: /usr/local/sbin/backup.sh
        mode: "0500"
        owner: root
        group: root
        create: yes
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
        block: |
          . /etc/bash/gaboshlib.include
          g_lockfile
          g_nice
          g_all-to-syslog
          g_echo_ok "Starting $0"
          set -o pipefail
          BACKUPDIR=/home/backup
          mkdir -p ${BACKUPDIR}
          chmod 700 ${BACKUPDIR}
          chown root:root ${BACKUPDIR}
          #find /usr/local/sbin/backup.d -name "*.backup" -type f | sort | while read backup
          for backup in $(find /usr/local/sbin/backup.d -name "*.backup" -type f | sort)
          do
            if bash -n "$backup" >$g_tmp/backup_error 2>&1
            then
               g_echo "Running: $backup"
               . "$backup"
             else
               g_echo_error "Error in $backup $(cat $g_tmp/backup_error)"
               continue
             fi
          done
          g_echo "Backup-Skript beendet"
        backup: yes
        validate: /bin/bash -n %s
      notify:

    - name: /usr/local/sbin/backup.sh shebang
      lineinfile:
        path: /usr/local/sbin/backup.sh
        insertbefore: BOF
        line: "#!/bin/bash"

    - name: /etc/cron.d/backup_local
      blockinfile:
        path: /etc/cron.d/backup_local
        create: yes
        mode: 0644
        owner: root
        group: root
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
        block: |
          5 0 * * * root /usr/local/sbin/backup.sh
        backup: yes



    - name: Register playbook as installed
      ansible.builtin.command: /usr/local/sbin/symbios-state.sh set base-services/backup.yml
      changed_when: false
