# SymbiOS - Debian-based server management platform
# Copyright (C) 2025  SymbiOS Contributors
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# docs:
#   short_description: Configure automated backups
#   description: Installs a scheduled backup job (cron) that backs up SymbiOS configuration and service data to the configured backup target.
#   author: Oliver Bohlen
#   version: '1.0'
#   license: GPLv3
#   copyright: Copyright 2026, Oliver Bohlen
#   min_ansible_version: '2.11'
#   platforms:
#   - name: Debian
#     versions:
#     - '13'
#   category: Backup
#   service_control:
#     services:
#     - name: backup
#       type: cron
#       file: /etc/cron.d/backup_local
#       status: test -f /etc/cron.d/backup_local || exit 2
#     logs:
#     - name: backup
#       command: tail -F /var/log/syslog | grep backup
#   actions:
#     enable: sed -i 's/^#//' /etc/cron.d/backup_local
#     disable: sed -i 's/^/#/' /etc/cron.d/backup_local
#     run now: /usr/local/sbin/backup.sh

---
- name: Backups
  hosts: all
  tasks:
    - name: Install Packages
      apt:
        name:
          - rsync
        update_cache: no
        install_recommends: no

    - name: Create checks dir /usr/local/sbin/backup.d
      ansible.builtin.file:
        path: /usr/local/sbin/backup.d
        owner: root
        group: root
        state: directory
        mode: '0700'

    - name: /usr/local/sbin/backup.sh
      ansible.builtin.copy:
        src: /home/SymbiOS/scripts/backup.sh
        dest: /usr/local/sbin/backup.sh
        mode: "0500"
        owner: root
        group: root
        backup: yes

    - name: /etc/cron.d/backup_local
      blockinfile:
        path: /etc/cron.d/backup_local
        create: yes
        mode: 0644
        owner: root
        group: root
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
        block: |
          5 0 * * * root /usr/local/sbin/backup.sh
        backup: yes



    - name: Register playbook as installed
      ansible.builtin.command: symbios-state.sh set base-services/backup.yml
      changed_when: false
