# docs:
#   short_description: Configure the host firewall with ufw
#   description: Installs and configures ufw, sets default deny policies and allows only the required services (SSH, HTTPS, etc.).
#   author: Oliver Bohlen
#   version: '1.0'
#   license: GPLv3
#   copyright: Copyright 2026, Oliver Bohlen
#   min_ansible_version: '2.11'
#   platforms:
#   - name: Debian
#     versions:
#     - '13'
#   category: Firewall / Network
#   service_control:
#     services:
#     - name: ufw
#       type: ufw
#       status: 'ufw status | grep -qi "Status: active"'
#     logs:
#     - name: firewall
#       command: tail -F -n 1000 /var/log/firewall.log
#     - name: ufw
#       command: tail -F -n 10000 /var/log/syslog | grep =ufw 
#   actions:
#     start: ufw --force enable
#     stop: ufw disable
#     reload: ufw reload
#

---

- name: Firewall with ufw
  hosts: all
  tasks:

    - name: Install Basic Packages
      apt:
        name: 
          - ufw
        update_cache: no
        install_recommends: no

    - name: Allow all access to tcp port 33 (ssh)
      community.general.ufw:
        rule: allow
        port: '33'
        proto: tcp

    - name: Allow chromecats port 8010 from all IPv4/IPv6 private networks
      community.general.ufw:
        rule: allow
        port: '8010'
        proto: tcp
        src: "{{ item }}"
      loop:
        - 10.0.0.0/8
        - 172.16.0.0/12
        - 192.168.0.0/16
        - fc00::/7

    - name: Deny everything per policy and enable UFW
      community.general.ufw:
        state: enabled
        policy: deny

