# SymbiOS - Debian-based server management platform
# Copyright (C) 2025  SymbiOS Contributors
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# docs:
#   short_description: Install system/service health checks
#   description: Deploys the runchecks health-check framework (script + systemd service) that periodically verifies critical services and reports their status.
#   author: Oliver Bohlen
#   version: '1.0'
#   license: GPLv3
#   copyright: Copyright 2026, Oliver Bohlen
#   min_ansible_version: '2.11'
#   platforms:
#   - name: Debian
#     versions:
#     - '13'
#   category: Monitoring / Checks
#   service_control:
#     services:
#     - name: runchecks
#       type: systemd
#       unit: runchecks.service
#       status: systemctl is-active runchecks.service
#     - name: runchecks
#       type: systemd
#       unit: runchecks.timer
#       status: systemctl is-active runchecks.timer
#     logs:
#     - name: runchecks.service
#       command: journalctl -fu runchecks.service -n 1000
#   actions:
#     start: systemctl start runchecks.service
#     stop: systemctl stop runchecks.service
#     restart: systemctl restart runchecks.service

---
- name: Checks
  hosts: all
  tasks:
    - name: Install Packages
      apt:
        name:
          - smartmontools
          - mdadm
        update_cache: no
        install_recommends: no

    - name: Create checks dir /usr/local/sbin/runchecks.d
      ansible.builtin.file:
        path: /usr/local/sbin/runchecks.d
        owner: root
        group: root
        state: directory
        mode: '0700'

    - name: /usr/local/sbin/runchecks.sh
      ansible.builtin.copy:
        src: /home/SymbiOS/scripts/runchecks.sh
        dest: /usr/local/sbin/runchecks.sh
        mode: "0500"
        owner: root
        group: root
      notify:
      - Restart runchecks

    - name: /usr/local/sbin/runchecks.d/services
      lineinfile:
        path: /usr/local/sbin/runchecks.d/services
        create: yes
        insertbefore: EOF
        line: "cron rsyslog sshd"

    - name: /etc/systemd/system/runchecks.service
      ansible.builtin.copy:
        dest: /etc/systemd/system/runchecks.service
        mode: "0444"
        owner: root
        group: root
        content: |
          [Unit]
          Description=checks
          After=syslog.target network.target
          
          [Service]
          Type=simple
          User=root
          ExecStart=/bin/bash /usr/local/sbin/runchecks.sh
          Restart=on-abort
          
          [Install]
          WantedBy=multi-user.target
      notify:
      - Restart systemd


    - name: /usr/local/sbin/runchecks.d/disks.check
      ansible.builtin.copy:
        src: /home/SymbiOS/scripts/runchecks.d/disks.check
        dest: /usr/local/sbin/runchecks.d/disks.check
        mode: "0400"
        owner: root
        group: root
        validate: /bin/bash -n %s
        backup: yes
      notify:
      - Restart runchecks

    - name: /usr/local/sbin/runchecks.d/raid-mdadm.check
      ansible.builtin.copy:
        src: /home/SymbiOS/scripts/runchecks.d/raid-mdadm.check
        dest: /usr/local/sbin/runchecks.d/raid-mdadm.check
        mode: "0400"
        owner: root
        group: root
        validate: /bin/bash -n %s
        backup: yes
      notify:
      - Restart runchecks
    
    - name: /usr/local/sbin/runchecks.d/internet.check
      ansible.builtin.copy:
        src: /home/SymbiOS/scripts/runchecks.d/internet.check
        dest: /usr/local/sbin/runchecks.d/internet.check
        mode: "0400"
        owner: root
        group: root
        validate: /bin/bash -n %s
        backup: yes
      notify:
      - Restart runchecks

    - name: /usr/local/sbin/runchecks.d/processes.check
      ansible.builtin.copy:
        src: /home/SymbiOS/scripts/runchecks.d/processes.check
        dest: /usr/local/sbin/runchecks.d/processes.check
        mode: "0400"
        owner: root
        group: root
        backup: yes
        validate: /bin/bash -n %s
      notify:
      - Restart runchecks

    - name: /usr/local/sbin/runchecks.d/thermal.check
      ansible.builtin.copy:
        src: /home/SymbiOS/scripts/runchecks.d/thermal.check
        dest: /usr/local/sbin/runchecks.d/thermal.check
        mode: "0400"
        owner: root
        group: root
        backup: yes
        validate: /bin/bash -n %s
      notify:
      - Restart runchecks

    - name: /usr/local/sbin/runchecks.d/measuretemp.check
      ansible.builtin.copy:
        src: /home/SymbiOS/scripts/runchecks.d/measuretemp.check
        dest: /usr/local/sbin/runchecks.d/measuretemp.check
        mode: "0400"
        owner: root
        group: root
        backup: yes
        validate: /bin/bash -n %s
      notify:
      - Restart runchecks

    - name: /usr/local/sbin/runchecks.d/load.check
      ansible.builtin.copy:
        src: /home/SymbiOS/scripts/runchecks.d/load.check
        dest: /usr/local/sbin/runchecks.d/load.check
        mode: "0400"
        owner: root
        group: root
        backup: yes
        validate: /bin/bash -n %s
      notify:
      - Restart runchecks

    - name: /usr/local/sbin/runchecks.d/services.check
      ansible.builtin.copy:
        src: /home/SymbiOS/scripts/runchecks.d/services.check
        dest: /usr/local/sbin/runchecks.d/services.check
        mode: "0400"
        owner: root
        group: root
        backup: yes
        validate: /bin/bash -n %s
      notify:
      - Restart runchecks

    - name: /usr/local/sbin/runchecks.d/df.check
      ansible.builtin.copy:
        src: /home/SymbiOS/scripts/runchecks.d/df.check
        dest: /usr/local/sbin/runchecks.d/df.check
        mode: "0400"
        owner: root
        group: root
        backup: yes
        validate: /bin/bash -n %s
      notify:
      - Restart runchecks

    - name: /usr/local/sbin/runchecks.d/dfinodes.check
      ansible.builtin.copy:
        src: /home/SymbiOS/scripts/runchecks.d/dfinodes.check
        dest: /usr/local/sbin/runchecks.d/dfinodes.check
        mode: "0400"
        owner: root
        group: root
        backup: yes
        validate: /bin/bash -n %s
      notify:
      - Restart runchecks

    - name: /usr/local/sbin/runchecks.d/freemem.check
      ansible.builtin.copy:
        src: /home/SymbiOS/scripts/runchecks.d/freemem.check
        dest: /usr/local/sbin/runchecks.d/freemem.check
        mode: "0400"
        owner: root
        group: root
        backup: yes
        validate: /bin/bash -n %s
      notify:
      - Restart runchecks

    - name: /usr/local/sbin/runchecks.d/freeswap.check
      ansible.builtin.copy:
        src: /home/SymbiOS/scripts/runchecks.d/freeswap.check
        dest: /usr/local/sbin/runchecks.d/freeswap.check
        mode: "0400"
        owner: root
        group: root
        backup: yes
        validate: /bin/bash -n %s
      notify:
      - Restart runchecks

    - name: 'add runchecks to startup'
      command: systemctl enable runchecks
      args:
        creates: /etc/systemd/system/multi-user.target.wants/runchecks.service

    - name: /usr/local/sbin/runchecks.d/symbios-healthcheck-runchecks.check
      ansible.builtin.copy:
        src: /home/SymbiOS/scripts/runchecks.d/symbios-healthcheck-runchecks.check
        dest: /usr/local/sbin/runchecks.d/symbios-healthcheck-runchecks.check
        mode: "0400"
        owner: root
        group: root
        backup: yes
        validate: /bin/bash -n %s

    - name: Deploy healthcheck for failed playbooks
      ansible.builtin.copy:
        src: /home/SymbiOS/scripts/runchecks.d/symbios-healthcheck-playbooks.check
        dest: /usr/local/sbin/runchecks.d/symbios-healthcheck-playbooks.check
        mode: "0400"
        create: yes
        owner: root
        group: root
        backup: yes
        validate: /bin/bash -n %s



    - name: Register playbook as installed
      ansible.builtin.command: symbios-state.sh set base-services/runchecks.yml
      changed_when: false
  handlers:

    - name: Restart systemd
      ansible.builtin.shell: systemctl daemon-reload
      notify: Restart runchecks

    - name: Restart runchecks
      service:
        name: runchecks
        state: restarted
