# SymbiOS - Debian-based server management platform
# Copyright (C) 2025  SymbiOS Contributors
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

log:
  level: ERROR

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
          permanent: true
  https:
    address: ":443"
    http:
      encodedCharacters:
        allowEncodedSemicolon: true
        allowEncodedPercent: true
        allowEncodedQuestionMark: true
        allowEncodedHash: true
  ldaps:
    address: ":636"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    directory: "/etc/traefik/providers.local"
    watch: true

api:
  dashboard: true

certificatesResolvers:
  letsencrypt:
    acme:
      httpChallenge:
        entryPoint: http
      email: "ssl@SymbiOS"
      storage: "/letsencrypt/acme.json"
  symbios-pki:
    acme:
      caServer: "https://acme-pki-stepca:9000/acme/acme/directory"
      email: "admin@localhost"
      storage: "/letsencrypt/symbios-pki-acme.json"
      httpChallenge:
        entryPoint: http

accessLog:
  filePath: "/log/access.log"
  format: json
