#!/bin/bash

# SymbiOS LDAP search wrapper - uses docker exec to bypass Traefik TLS
. /home/docker/ldap/env.openldap

docker compose -f /home/docker/ldap/docker-compose.yml exec -T openldap \
  ldapsearch -x -H ldap://localhost -D "cn=readuser,dc=openldap,dc=local" -w "$LDAP_READUSER_PASSWORD" -b "dc=openldap,dc=local" "$@"
g_rc=$?

# Clear credentials from environment
unset LDAP_ADMIN_PASSWORD LDAP_READUSER_PASSWORD

exit $g_rc
