#!/bin/bash
# SymbiOS - Generate the settings fields reference from script schemas.
#
# Prints (or writes/checks) a Markdown reference of every
# symbios-settings-*.sh schema: one section per script with its field
# table. Generated file: settings-fields.md at the repo root (see DOCS.md
# ownership). Regenerate after any schema change; --check fails on drift
# (CI gate). Runs wherever bash + python3 exist - schema output needs no
# inventory, only the scripts directory.
#
# Usage: symbios-settings-docs.sh [--write FILE | --check FILE]
#   (no args: print to stdout)
#
# Exit codes: 0 ok / identical, 1 drift or technical error.

function f_usage {
  cat << EOF
Usage: $(basename "$0") [--write FILE | --check FILE]

Generate the settings fields reference (settings-fields.md) from every
symbios-settings-*.sh schema subcommand.

  (no args)       Print the reference to stdout
  --write FILE    Write the reference to FILE (with generated header)
  --check FILE    Exit 1 when FILE differs from the generated reference

Exit codes:
  0  ok (or identical, for --check)
  1  drift detected, unknown script failure, or usage error
EOF
}

f_mode="print"
f_file=""

while [[ $# -gt 0 ]]
do
  case "$1" in
    --write)
      [[ $# -ge 2 ]] || { f_usage >&2; exit 1; }
      f_mode="write"
      f_file="$2"
      shift 2
      ;;
    --check)
      [[ $# -ge 2 ]] || { f_usage >&2; exit 1; }
      f_mode="check"
      f_file="$2"
      shift 2
      ;;
    -h|--help)
      f_usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      f_usage >&2
      exit 1
      ;;
  esac
done

g_symbios_dir="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")" )" && pwd)"

f_failures=0
f_out=""

f_out+='# SymbiOS Settings Fields Reference
'
f_out+='<!-- GENERATED by scripts/symbios-settings-docs.sh - do not edit by hand. -->'
f_out+=$'\n'
f_out+='Field schemas of every `symbios-settings-*.sh` script (`schema`'
f_out+=' subcommand). The slug maps to `/settings/<slug>/` for settings'
f_out+=' pages; companion scripts (filemanager, setup) serve other endpoints.'
f_out+=$'\n\n'

for f_script in "${g_symbios_dir}"/symbios-settings-*.sh
do
  case "${f_script}" in
    *-lib.sh|*-new.sh|*-check.sh|*-docs.sh) continue ;;
  esac
  [[ -x "${f_script}" ]] || continue
  f_base="$(basename "${f_script}" .sh)"
  f_slug="${f_base#symbios-settings-}"
  if ! f_schema="$("${f_script}" schema 2>/dev/null)"
  then
    echo "Cannot read schema from ${f_base}" >&2
    f_failures=$((f_failures + 1))
    continue
  fi
  f_table="$(printf '%s' "${f_schema}" | python3 -c '
import json, sys

def fmt_default(v):
    if v is None or v == "":
        return ""
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (list, dict)):
        return "`%s`" % json.dumps(v)
    return str(v)

try:
    schema = json.load(sys.stdin)
except Exception as e:
    sys.exit("invalid schema JSON: %s" % e)
fields = schema.get("fields", schema) if isinstance(schema, dict) else schema
if not isinstance(fields, list):
    sys.exit("invalid schema shape")
print("| Name | Type | Label | Required | Default | Secret |")
print("|------|------|-------|----------|---------|--------|")
for raw in fields:
    if not isinstance(raw, dict) or not raw.get("name"):
        continue
    name = str(raw["name"])
    ftype = str(raw.get("type") or "text")
    label = str(raw.get("label") or name).replace("|", "/")
    req = "yes" if raw.get("required") else ""
    default = fmt_default(raw.get("default")).replace("|", "/")
    secret = "yes" if raw.get("secret") else ""
    print("| `%s` | %s | %s | %s | %s | %s |" % (name, ftype, label, req, default, secret))
' 2>&1)" || {
    echo "Cannot parse schema from ${f_base}: ${f_table}" >&2
    f_failures=$((f_failures + 1))
    continue
  }
  f_out+="## \`${f_base}\`"
  f_out+=$'\n'
  f_out+="Slug: \`${f_slug}\`"
  f_out+=$'\n\n'
  f_out+="${f_table}"
  f_out+=$'\n\n'
done

if [[ "${f_failures}" -gt 0 ]]
then
  echo "${f_failures} script(s) unreadable" >&2
  exit 1
fi

case "${f_mode}" in
  print)
    printf '%s' "${f_out}"
    ;;
  write)
    printf '%s' "${f_out}" > "${f_file}"
    echo "Wrote ${f_file}"
    ;;
  check)
    if [[ ! -f "${f_file}" ]]
    then
      echo "Missing file: ${f_file}" >&2
      exit 1
    fi
    if cmp -s <(printf '%s' "${f_out}") "${f_file}"
    then
      echo "settings-fields.md matches generated reference"
    else
      echo "Drift detected: ${f_file} differs from generated reference" >&2
      echo "Run: symbios-settings-docs.sh --write ${f_file}" >&2
      exit 1
    fi
    ;;
esac
exit 0
